### ISSUE TITLE
Bug: Unable to create kde plots due to error "ValueError: window_length must be odd"

### ISSUE THREAD

**Issue by emanuelsc87** [soorajachar/plateypus#8]
I get the error shown below when trying to plot Single Cell kde's. I shared with you the dataframe, and I'm copying the steps followed to create a test figure with kde plots (for the last step, I left the default values). When trying the same steps for histograms, it worked fine (see figure at the end).
Thanks!!

![image](https://user-images.githubusercontent.com/52220284/121090321-6b1d7500-c7b6-11eb-9930-a5741a95c39b.png)
![image](https://user-images.githubusercontent.com/52220284/121089886-c8fd8d00-c7b5-11eb-91e1-4ccf3ecd3c4c.png)
![image](https://user-images.githubusercontent.com/52220284/121089973-e4689800-c7b5-11eb-8fa7-add59fef1dbe.png)
![image](https://user-images.githubusercontent.com/52220284/121090055-fe09df80-c7b5-11eb-8bec-b188a07f8296.png)

![image](https://user-images.githubusercontent.com/52220284/121090402-8c7e6100-c7b6-11eb-8155-e00b27c9ce40.png)

**Comment by soorajachar** [comment]
Try increasing the smoothing window by 1 on the last screen as a quick fix right now

**Comment by emanuelsc87** [comment]
Default is 27, and I could an only increase or decrease by 2, and it gives the same error. It's weird because the values are indeed odd values.

**Comment by soorajachar** [comment]
This is actually very strange as my default is 28 and it works fine for me: 
<img width="716" alt="Screen Shot 2021-06-08 at 4 28 22 AM" src="https://user-images.githubusercontent.com/49458891/121150963-f7a95100-c811-11eb-8823-e0f9d557fd76.png">
![temporaryFirstPlot](https://user-images.githubusercontent.com/49458891/121151048-098af400-c812-11eb-88c2-9b14a7b10852.png)
However our code is identical... I'll have to take a deeper look into this. Hopefully the histograms are good enough for you right now.

**Comment by soorajachar** [comment]
In the meantime though I've pushed an update (0.2.3) that should hopefully fix the problem by making sure the filtering value is odd (and if not subtracting 1) before passing it to the smoothing function. This was the point of starting the slider at an odd number and only allowing a user to increment it by 2 in the first place but somehow that wasn't enough (?). Once you've confirmed it works for you let me know and I'll close the issue, as right now my default is 28 for some reason so I can't really check to make sure the solution worked myself.

**Comment by emanuelsc87** [comment]
Thank you so much! That fixed the problem. It was almost neccesary to use kde's instead of histograms because I needed to create 30 plots as the one below, and with histograms multiple overlayed curves don't look good.
It's so nice with these plots because we will be able to assess easily the specific signal in the intended channel, and the unintended signal or spread caused during unmixing in the rest of the channels. Thanks again!

![image](https://user-images.githubusercontent.com/52220284/121190696-4cac8d80-c839-11eb-9742-7d2da44e61a7.png)

**Comment by soorajachar** [comment]
Fixed in 0.2.3
